### ISSUE TITLE
Error while connecting Metamask 📕

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fair-portal#14]
First, there is an endless loading indicator line, and when trying to Connect

with the Connect button, and approving on Metamask's window this happens:
<img width="727" alt="Screenshot 2024-04-15 at 15 42 51" src="https://github.com/fairDataSociety/fair-portal/assets/81620050/7a818a7c-b490-42d7-bee1-460c7800c1e2">

_tested on usual intel Mac._

**Comment by tomicvladan** [comment]
@tamas6  Which URL are you using to access the app?

**Comment by tamas6** [comment]
> @tamas6 Which URL are you using to access the app?

this  would be: 

https://fairdrive.fairdatasociety.org/apps/fportal/

**Comment by tomicvladan** [comment]
Try doing a hard reload of the app. And before connecting, change the network in Metamask to Sepolia. Unfortunately at the moment automatic network change is not implemented.

**Comment by tomicvladan** [comment]
Now you should see an error message if selected network is wrong. I'll close this issue and if you encounter this error again please open another one.

**Comment by tamas6** [comment]
> Now you should see an error message if selected network is wrong. I'll close this issue and if you encounter this error again please open another one.

Great, great!
